# Generated by Django 5.0.1 on 2025-11-19 04:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('appliance', 'Appliance Repair'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('carpentry', 'Carpentry'), ('locksmith', 'Locksmith'), ('gardening', 'Gardening'), ('pest_control', 'Pest Control'), ('general_maintenance', 'General Maintenance'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('estimated_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('icon', models.CharField(default='wrench', help_text='Icon name for UI display', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Catalog',
                'verbose_name_plural': 'Service Catalog',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='admin_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='admin_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who confirmed the service booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_service_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='admin_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if booking was rejected by admin'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='booking_type',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='requested_date',
            field=models.DateField(blank=True, help_text='Preferred date for service', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='requested_time',
            field=models.TimeField(blank=True, help_text='Preferred time for service', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='service_catalog',
            field=models.ForeignKey(blank=True, help_text='Pre-defined service from catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='maintenance.servicecatalog'),
        ),
    ]
