# Generated by Django 5.0.1 on 2025-11-12 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('property_tax', 'Property Tax'), ('insurance', 'Insurance'), ('hoa_fees', 'HOA Fees'), ('maintenance', 'Maintenance'), ('repairs', 'Repairs'), ('cleaning', 'Cleaning'), ('mortgage', 'Mortgage Payment'), ('management_fee', 'Management Fee'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], max_length=20, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Expense',
                'verbose_name_plural': 'Property Expenses',
                'db_table': 'property_expenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['property', 'expense_date'], name='property_ex_propert_ace006_idx'), models.Index(fields=['property', 'category'], name='property_ex_propert_dc51ac_idx')],
            },
        ),
    ]
