# Generated by Django 5.0.1 on 2025-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approval_type',
            field=models.CharField(choices=[('landlord', 'Landlord Approval'), ('admin', 'Admin Approval')], default='landlord', help_text='Who should approve booking requests for this property', max_length=20),
        ),
    ]
